#!/usr/bin/env bash
#

UUID=`blkid -s UUID -o value /dev/${partition2}`  # Узнать UUID корневого диска
arch-chroot /mnt /bin/bash -c "bootctl install"
{
    echo "default arch.conf"
    echo "timeout menu-force"
    echo "console-mode auto"
    echo "editor no"
} >> /mnt/boot/loader/loader.conf
#-------
{
    echo "title    Arch Linux"
    echo "linux    /vmlinuz-linux"
    echo "initrd    /${proc_ucode}.img"
    echo "initrd    /initramfs-linux.img"
} >> /mnt/boot/loader/entries/arch.conf
#-------
{
    echo "title    Arch Linux fallback"
    echo "linux    /vmlinuz-linux"
    echo "initrd    /${proc_ucode}.img"
    echo "initrd    /initramfs-linux-fallback.img"
} >> /mnt/boot/loader/entries/arch-fb.conf
#-------
echo "options    root=UUID=${UUID}" >> /mnt/boot/loader/entries/arch.conf
sed -i "/^options/ s|$| $(tr '\n' ' ' < $(dirname $0)/sources/kernel_options)|; s/ $//" /mnt/boot/loader/entries/arch.conf
echo "options    root=UUID=${UUID}" >> /mnt/boot/loader/entries/arch-fb.conf
sed -i "/^options/ s|$| $(tr '\n' ' ' < $(dirname $0)/sources/kernel_options)|; s/ $//" /mnt/boot/loader/entries/arch-fb.conf
